esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  includes:
    - haier.h

substitutions:
  devicename: "haier"

logger:
  level: DEBUG
  baud_rate: 0 #Important. You can't use serial port

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: 192.168.5.124
    gateway: 192.168.5.1
    subnet: 255.255.255.0

# Enable Home Assistant API
api:
  password: !secret api_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  topic_prefix: esphome/$devicename
  birth_message:
    topic: esphome/$devicename/availability/topic
    payload: online
  will_message:
    topic: esphome/$devicename/availability/topic
    payload: offline


ota:
  password: !secret ota_password

web_server:
  port: 80

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Samara

climate:
  - platform: custom
    lambda: |-
      auto haier = new Haier();
      App.register_component(haier);
      return {haier};
    climates:
      - name: "Haier"
